name: 'Run Docker on LAN'
description: 'Runs a Docker image on a self-hosted runner in your LAN'

inputs:
  image:
    description: 'The Docker image to run'
    required: true
    default: 'iscanprint/prospersllc:3.1'
  port:
    description: 'Port mapping from local machine to container'
    required: true
    default: '8080:80'

runs:
  using: 'docker'
  steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image
      run: |
        docker pull iscanprint/prospersllc:3.1

    - name: Run Docker container on LAN
      run: |
        docker run -d -p 8080:80 --name prosperllc iscanprint/prospersllc:3.1

    - name: Display container logs (optional)
      run: |
        docker logs prosperllc
